version: "3.9"
services:
  kali:
    image: acodeninja/kali:latest
    ports:
      - '6080:6080'
    environment:
      RESOLUTION: 1920x1080x24
      TZ: Europe/London
    volumes:
      - type: bind
        source: ./
        target: /root/host
    links:
      - diwa
      - goat
      - dvwa

  goat:
    image: webgoat/goatandwolf
    ports:
      - '8001:80'
    environment:
      TZ: Europe/London
      WEBGOAT_PORT: 80

  diwa:
    image: acodeninja/diwa
    ports:
      - '8000:80'
    environment:
      TZ: Europe/London

  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - '8002:80'
    environment:
      TZ: Europe/London
